sr = 44100
sound_speed = 333
out_dir = './out/rottest/'

walls = [[[0,5,0], [1,0,0], [0,0,1]]]

[sources]
    [sources.source0]
        position=[10,3,5]
        name='box'
        audio_file='./audio/dernkala.wav'

    [sources.source1]
        position=[10,-3,3]
        name='ander'
        audio_file='./audio/dernkala.wav'
 
[array]
 mic_type = './config/testMic.toml'
 array_config = './config/array.toml'
 center=[0,0,1]
 normal=[1,1,1]
