sr = 48000
sound_speed = 333
out_dir = './out/synth/'

[sources]
    [sources.source0]
        position=[10,3,5]
        name='box'
        audio_file='./audio/drone.wav'

    [sources.source1]
        position=[10,-3,8]
        name='box'
        audio_file='./audio/dernNoise.wav'

 [array]
 mic_type = './config/noisyMic.toml'
 array_config = './config/array.toml'
